version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./static/reports:/app/static/reports
      - ./static/plots:/app/static/plots
    environment:
      - FLASK_ENV=production
    restart: always
    command: python app.py
